= Dynamic properties

In order to make your microservices deployment easier, you want to have a way to dynamically retrieve
resources configuration according to your business needs. Imagine you need to change the database
username configured in some `system.properties` file across 100's TomEE servers. If changing all the
100's of `system.properties` or redeploying all the servers is not an option, you could use the
`properties-provider` feature from Apache TomEE.

== How does this work?

You write your `resources.xml` file in a way that it uses a `properties-provider` object to retrieve the properties
for you. Example:


```
<?xml version="1.0" encoding="UTF-8"?>
<resources>
    <Resource id="movieDatabase" type="DataSource" properties-provider="org.superbiz.PropertiesService">
        JdbcDriver com.mysql.jdbc.Driver
        JdbcUrl    jdbc:mysql://$[db.host]/movies
        UserName   $[db.username]
        Password   $[db.password]
    </Resource>
</resources>
```


In the block above you will notice the `properties-provider` attribute. It specifies the class TomEE will use to
retrieve the `$[db.host]`, `$[db.username]` and `$[db.password]` values.


```
public class PropertiesService implements PropertiesResourceProvider {

    private Properties properties;

	// (1) TomEE will provide "properties" from the
	// resource definition by calling this setter.
	// If "properties" has no setter, TomEE you
	// inject the values directly into the "properties"
	// property.
    public void setProperties(Properties properties) {
        this.properties = properties;
    }

    @Override
    public Properties provides() {
	  // (2) this method *must* return *all* the
	  // properties for the resource, and the
	  // values *must* be the final values. No
	  // further substitution, trimming or other
	  // manipulation will be performed.
	  return result;
    }
}
```


Lets do something similar but by using both variable replacement from default TomEE properties provider and a custom
properties provider. We will retrieve our values by loading content from a URI like
`file:///opt/servers.properties#cassandra_servers`, where `#cassandra_servers` is the key inside the
`servers.properties` resource.


```
<resources>
    <Resource id="info" class-name="com.tomitribe.support.Info" properties-provider="com.tomitribe.support.PropertiesService">
        hostname ${hostname}
        zookeeperServers ${servers.zookeeper}
        cassandraServers ${servers.cassandra}
    </Resource>
</resources>
```


The TomEE server will load system properties first. Imagine we have a system.properties like this...


```
hostname=file:///etc/hostname
servers.zookeeper=file:///opt/servers.properties#zookeeper_servers
servers.cassandra=file:///opt/servers.properties#cassandra_servers
```


After TomEE replaces the `${}` values with the values from this `system.properties`, the same `resources.xml` will look
like this in memory...


```
<resources>
    <Resource id="info" class-name="com.tomitribe.support.Info" properties-provider="com.tomitribe.support.PropertiesService">
        hostname file:///etc/hostname
        zookeeperServers file:///opt/servers.properties#zookeeper_servers
        cassandraServers file:///opt/servers.properties#cassandra_servers
    </Resource>
</resources>
```


Now our custom provider can replace the URI values with the data from the remote resources.

=== Relevant sample code

* The custom resource class: https://github.com/tomitribe/demo-dynamic-properties/blob/master/custom-resource/src/main/java/com/tomitribe/support/Info.java
* The `PropertiesResourceProvider` that will retrieve the final values for us: https://github.com/tomitribe/demo-dynamic-properties/blob/master/properties-provider/src/main/java/com/tomitribe/support/PropertiesService.java
* The Rest API to load the final results: https://github.com/tomitribe/demo-dynamic-properties/blob/master/simple-app/src/main/java/com/tomitribe/support/ApiInfo.java

== How to test it?

If you want to test it locally, first build this project with `mvn clean install`. Now you can execute
`mvn tomee:run --projects simple-app/` to run Apache TomEE locally.

If you want to test it with docker, simply run `docker run --rm -ti -p 8080:8080 tomitribe/demo-dynproperty` for TomEE 7.0.3.

For TomEE 1.7.4, run `docker run --rm -ti -p 8080:8080 tomitribe/demo-dynproperty:1.7.x-0.0.1-SNAPSHOT`.

Services available here:

* http://localhost:8080/api/info/

== External resources

* http://tomee.apache.org/application-resources.html
* https://rmannibucau.wordpress.com/2014/08/06/tomee-and-more-advanced-resource-configuration/
* https://support.tomitribe.com/hc/en-us/articles/115013878408-Using-the-Properties-resource-provider






