= Dynamic properties

In order to make your microservices deployment easier, you want to have a way to dynamically retrieve
resources configuration according to your business needs. Imagine you need to change the database
username configured in some `system.properties` file across 100's TomEE servers. If changing all the
100's of `system.properties` or redeploying all the servers is not an option, you could use the
`properties-provider` feature from Apache TomEE.

== How does this work?

You write your resources.xml file in a way that it uses a `properties-provider` to retrieve the properties
dynamically for you. Example:

```
<?xml version="1.0" encoding="UTF-8"?>
<resources>
    <Resource id="movieDatabase" type="DataSource" properties-provider="org.superbiz.PropertiesService">
        JdbcDriver com.mysql.jdbc.Driver
        JdbcUrl    jdbc:mysql://$[db.host]/movies
        UserName   $[db.username]
        Password   $[db.password]
    </Resource>
</resources>
```

In the block above you will notice the `properties-provider` attribute. It specifies the class TomEE will use to
retrieve the `$[db.host]`, `$[db.username]` and `$[db.password]` values.

Lets do something similar to what the Apache HTTPd server has. We will retrieve our values by loading content
a URI like `file:///opt/servers.properties#cassandra_servers`, where `#cassandra_servers` is the key inside the
`servers.properties` resource.

Let's write a custom property class and use if with a properties provider to load values from URIs.

```
<resources>
    <Resource id="info" class-name="com.tomitribe.support.Info" properties-provider="com.tomitribe.support.PropertiesService">
        hostname ${hostname}
        zookeeperServers ${servers.zookeeper}
        cassandraServers ${servers.cassandra}
    </Resource>
</resources>
```

The TomEE server will load system properties first. Imagine we have a system.properties like this...

```
hostname=file:///etc/hostname
servers.zookeeper=file:///opt/servers.properties#zookeeper_servers
servers.cassandra=file:///opt/servers.properties#cassandra_servers
```

After TomEE replaces the `${}` values with the values from this `system.properties`, the same `resources.xml` will look
like this in memory...

```
<resources>
    <Resource id="info" class-name="com.tomitribe.support.Info" properties-provider="com.tomitribe.support.PropertiesService">
        hostname file:///etc/hostname
        zookeeperServers file:///opt/servers.properties#zookeeper_servers
        cassandraServers file:///opt/servers.properties#cassandra_servers
    </Resource>
</resources>
```

Now our custom provider can replace the URI values with the data from the remote resources.

=== Important classes

* The custom resource class: https://github.com/tomitribe/demo-dynamic-properties/blob/master/custom-resource/src/main/java/com/tomitribe/support/Info.java
* The `PropertiesResourceProvider` that will retrieve the final values for us: https://github.com/tomitribe/demo-dynamic-properties/blob/master/properties-provider/src/main/java/com/tomitribe/support/PropertiesService.java
* The Rest API to load the final results: https://github.com/tomitribe/demo-dynamic-properties/blob/master/simple-app/src/main/java/com/tomitribe/support/ApiInfo.java

== How to test it?

If you want to test it locally, first build this project with `mvn clean install`. Now you can execute
`mvn tomee:run --projects simple-app/` to run Apache TomEE locally.

If you want to test it with docker, simply run `docker run --rm -ti -p 8080:8080 tomitribe/demo-dynproperty` or
`docker-compose -f stack.yaml up`

Services available here:

* http://localhost:8080/api/info/
* in case you are using docker-compose, you will also see http://localhost:8081/api/info/

== External resources

* http://tomee.apache.org/application-resources.html
* https://rmannibucau.wordpress.com/2014/08/06/tomee-and-more-advanced-resource-configuration/








